version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - djangonetwork
  db:
    image: postgres:11
    networks:
      - djangonetwork
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

networks:
  djangonetwork:
    driver: bridge
